### ISSUE TITLE
MarlinStdReco Paths in Calibration File

### ISSUE THREAD

**Issue by ueinhaus** [iLCSoft/ILDConfig#101] opened 2019-05-16 12:38 UTC
At the moment, the MarlinStdReco steering file can only be used in the working directory .../production/ because there are absolute paths not only in the steering file itself but also in the calibration files, namely referring to the Pandora settings and the HighLevelReco PID files.
It would be beneficial to change these absolute paths to relative ones or have a dedicated constant in the MarlinStdReco steering file specifying the production folder to be used, so this can be changed in the steering file only, and then the steering file can be run from anywhere.

**Comment by rete** [comment] 2019-05-16 13:25
Hi Uli,

thank for reporting this issue. 

I had a look and it seems that the `PandoraSettingsDefault.xml` file also references another file called `PandoraLikelihoodData9EBin.xml` which you can also find in the `PandoraSettings` directory. Unfortunately, the path of this file can't be changed at runtime because this XML file is parsed by PandoraPFA itself and has to be hardly set. So we don't have yet a mechanism to allow for setting a constant to all scripts yet. 
I keep this issue opened for future investigations.

Thanks again

**Comment by rete** [comment] 2019-12-09 17:21
Closing this issue as it can't be solved by us. 

The only solution is to run Marlin in the `StandardConfig/production`, as the path to `PandoraLikelihoodData9EBin.xml` is a relative path and can't be changed at runtime.

The issue is at least documented.

**Closed by rete** 2019-12-09 17:21 UTC
Labels: enhancement
